### ISSUE TITLE
Create standard mounting system for cars

### ISSUE THREAD

**Issue by rdragonz** [nlMeminger/MagiCarp#9]
An enclosure for the project needs to be created that allows for the equipment to be mounted in a standard Double-DIN car radio slot. This should include standard input and output jacks for car radio systems including connections for power and ignition. This is an **ULTRA LOW PRIORITY** issue.

**Comment by nlMeminger** [comment]
This is actually higher than you’d think, and is in progress now

**Comment by nlMeminger** [comment]
The pi and pi screen for our first prototype is fully mounted into my car, so I am considering this complete for now.  Eventually we will also share the digital files used to 3D print everything.
